### ISSUE TITLE
Autocomplete Less Functions or CSS

### ISSUE THREAD

**Issue by sacerro** [Crunch/Crunch-2#101]
For example: if you are using width property it should show avaible options for this property:

width: auto|value|initial|inherit

This feature would be great for new developers

For mixins it should show params

**Comment by matthew-dean** [comment]
Do you know you filed this same issue on Sep 7? Closing as duplicate of #54.

**Comment by sacerro** [comment]
oh! Sorry. I think this issue was solved in beta 9 (or beta 10, don't remember).
