### ISSUE TITLE
Parse error with CSS transformations

### ISSUE THREAD

**Issue by chris-propoint** [Crunch/Crunch-2#102]
Getting a parse error for any of these three lines:

-ms-transform: rotate(355deg);
-webkit-transform: rotate(355deg);
transform: rotate(355deg);

I haven't tried other transformations, animations, or transitions yet, but I hope they're all supported soon.

**Comment by matthew-dean** [comment]
Crunch doesn't parse your code; it passes it to the compiler. So if it's a parsing error, that error is coming from Less and Crunch is just displaying it.

Closing as not a Crunch issue.
