### ISSUE TITLE
Taskbar Hides Scrollbar Arrow

### ISSUE THREAD

**Issue by Pantyboy** [Crunch/Crunch-2#105]
Hi Matt

Think I've found an issue here.

The taskbar cover the "down" arrow of the vertical scrollbar.

I've attached a screenshot to show what I'm whittering on about.

Regards

Pb

![crunch-taskbar](https://cloud.githubusercontent.com/assets/6214205/10803827/3192c1c2-7dbc-11e5-81eb-3237e1b62451.jpg)

**Comment by matthew-dean** [comment]
I didn't know about that exact behavior, but I do know the reason for it, which has now been fixed and will be in the next release.

**Comment by Pantyboy** [comment]
Fabbo!
