### ISSUE TITLE
Crash while compiling on Mac requires deletion of ~/Library/Application Support/Crunch2 to fix

### ISSUE THREAD

**Issue by vtortelli** [Crunch/Crunch-2#106]
First issue: 
compiling stated complete, but finished compiled file had not changed. After the third compile attempt, the app crashed.

Second: After force quitting the app, and restarting, Crunch2 app would not finish loading.
Deleting ~/Library/Application Support/Crunch2 and restarting fixed the problem.

Running Mac OS 10.10.5

![screen shot 2015-10-28 at 9 17 39 pm](https://cloud.githubusercontent.com/assets/10962758/10809469/af1d9270-7dbc-11e5-9911-9dc6fccd8116.png)

**Comment by matthew-dean** [comment]
Well, that's not good, and hard to debug. My best guess - there was a problem with access to a write location, but it saved the path to the write location anyway, which caused an error on reload, or something along those lines. I'll need to put in something to at least log the crash reason, and maybe automatically reset app state on reload if there's a crash.

**Comment by matthew-dean** [comment]
The next release will have better error handling / messaging. See: #104. That won't necessarily help you if this happens again, but it will help me help you if this happens again.

**Comment by vtortelli** [comment]
Perfect! Thanks.

**Comment by matthew-dean** [comment]
Fixed in beta 11.
