### ISSUE TITLE
Undo not working?

### ISSUE THREAD

**Issue by Pantyboy** [Crunch/Crunch-2#107]
Hi Matt

This may not be implemented yet and if so, please accept my apologies for being a bit previous, but (in Windows 10, Crunch 2 Pro, Beta 10) Ctrl+Z or Edit>>Undo doesn't work.

Regards

Pb

**Comment by matthew-dean** [comment]
It's definitely a bug. There's no reason Undo shouldn't work. May be a Windows-only bug. I'll check it out.

**Comment by Pantyboy** [comment]
Hi Matt

This appears to be a case of problem between the chair and the keyboard. I must have done something (or not done something, whichever the case) as it's now working, so I'll close this issue.

Sorry about that.

Regards
Pb

**Comment by matthew-dean** [comment]
> This appears to be a case of problem between the chair and the keyboard. 

Have you tried turning yourself off and on again?

**Comment by Pantyboy** [comment]
That's something I try not to do very often. I'm of an age where the battery takes a little longer to recharge and then runs down a lot quicker than it used to. I'm also a little worried that my hard drive is seeping data. Luckily, I have backups, it's just I can't remember where they are
