### ISSUE TITLE
Save later...

### ISSUE THREAD

**Issue by xubing6243** [Crunch/Crunch-2#112]
Save later,Cursor runing to first line.Folding code automatically opens! This feeling is not very good, please solve.

TO: mac Version 2.0.5-beta.10

**Comment by matthew-dean** [comment]
Sorry, I don't understand.

**Comment by mbl-at** [comment]
After each save, cursor goes to first line;
A little bit disturbing, if you hit ctrl+s many times.

Windows 7 x64 professional / Version 2.0.8-RC.1

**Comment by matthew-dean** [comment]
Ah. This is actually the same as: #128, which is fixed and hopefully I can release soon.
