### ISSUE TITLE
Compiling fails for Joomla 3 Protostar template which works with Crunch 1

### ISSUE THREAD

**Issue by kukwm** [Crunch/Crunch-2#115]
Hi,
I work with Crunch 1 to compile my less project which base on Joomla's Protostar template (version 3.4.5) which uses the same less files like Joomla core. It works fine. 

Compiling fails in Crunch 2 for the same project with this error: "Whoops! There was a name error while crunching template.less in file navbar.less on line 199." This points to a core Joomla less file which I use only and never change(d).

I reported this because (1) I cannot see an error in this file/line and (2) I have no issues in Crunch 1.
Perhaps this is a bug or not. Fact is that I do not know what the differences are between Crunch 1/2. Do it await a certain bootstrap version (2 or 3?, Joomla 3 works with 2) and/or a certain less version?

Thanks.

**Comment by matthew-dean** [comment]
This is likely a bootstrap compiling error. Early versions of bootstrap don't compile with Less > 2.0. Crunch 1 uses a pre 2.0 version of Less. Crunch 2 uses latest version.

What's at line 199? Since I'm a Less core contributor I may be able to identify it.

**Comment by kukwm** [comment]
Here the relevant code in navbar.less in Joomla JUI. Error points to: #grid > .core > .span(@gridColumns);


// Reset container width
// Required here as we reset the width earlier on and the grid mixins don't override early enough
.navbar-static-top .container,
.navbar-fixed-top .container,
.navbar-fixed-bottom .container {
  #grid > .core > .span(@gridColumns);
}

**Comment by matthew-dean** [comment]
Hmm, nothing jumps out at me from the example. Is template.less importing bootstrap.less?

**Comment by kukwm** [comment]
Yes. But I think that all your question can be answered when you install Joomla 3.4.5 with default settings. It uses the template 'Protostar' as default. In folder ../templates/protostar/less/template.less you will find the file which I mean. I used this template as base for my own template because I want to use the bootstrap which is included in Joomla already. Joomla 3.4.5 works with Bootstrap version 2.3.2. Can this cause the compiling error?

**Comment by matthew-dean** [comment]
> But I think that all your question can be answered when you install Joomla 3.4.5 with default settings

Er, sorry, that's really not something I have time for. This would be a question to bring up in Less: https://github.com/less/less.js, or, probably with better success, to bring up with whomever created the protostar template, as it's not a Crunch issue.
