### ISSUE TITLE
Error:TypeError

### ISSUE THREAD

**Issue by Pantyboy** [Crunch/Crunch-2#124]
Hi Matt
Here's one for you. I've attached a screen shot to save me writing it all out (lazy or what?).

![untitled-1](https://cloud.githubusercontent.com/assets/6214205/11132847/4f386b3a-898a-11e5-9dd6-f096156321df.jpg)

I get this error when I change a .less file and use CTRL+S to Crunch.
If I Crunch from the 'File' menu, there is no problem.
I'm using Crunch Pro 2.0.5 beta 11 on Windows 10 64bit
 
Regards
Pb

**Comment by matthew-dean** [comment]
I would have thought this was error #114 (discovered when I accidentally tried to crunch from my output .css file), but that should be fixed. Now that beta 11 has proper error logs I'll see if I can find more information about this one. Thanks for reporting.

**Comment by Pantyboy** [comment]
Hi Matt
I forgot to mention that it does save the alteration to the .less file but something strange happens when I open Crunch again. See [#125](https://github.com/Crunch/Crunch-2/issues/125).

**Comment by matthew-dean** [comment]
Looks like this is happening with enough frequency that I'm going to go ahead and create a new release with the fix today (beta 12). Will be up soon.

**Comment by matthew-dean** [comment]
Done. See if this fixes it (and curious if it fixes the text display problem) - https://github.com/Crunch/Crunch-2/releases/tag/v2.0.5-beta.12
