### ISSUE TITLE
Strange display when opening Crunch after Error:TypeError

### ISSUE THREAD

**Issue by Pantyboy** [Crunch/Crunch-2#125]
Hi Matt

I think this is explained by this screen shot.

![untitled-2](https://cloud.githubusercontent.com/assets/6214205/11133350/44615b4c-898d-11e5-9f7b-17ce9dde11eb.jpg)

When I check out the .less file in a text editor, it's fine but it takes opening and closing Crunch a couple of times to rectify the problem,

However, this could just be me.

Regards

Pb

**Comment by matthew-dean** [comment]
Hmm, looks like it's an issue of incorrect text encoding. Do you know what the encoding is? And what encoding it's opened as in the other editor?

**Comment by mbl-at** [comment]
Happened to me too once.

**Comment by Pantyboy** [comment]
Hi Matt.

I have no idea about the encoding as the .less and .css files were created within Crunch. The text editor document properties shows them as being opened as UTF-8.

Regards
Pb

**Comment by matthew-dean** [comment]
I wonder if it has something to do with: https://github.com/nodejs/node-v0.x-archive/issues/1918

**Comment by matthew-dean** [comment]
Just to clarify: the file is scrambled in Crunch, but if you open the same file in another text editor, it shows unscrambled and the encoding is still UTF-8?

**Comment by Pantyboy** [comment]
Hi Matt
Yep, that's correct.

**Comment by Pantyboy** [comment]
Hi Matt

Just updated Crunch to beta.12 and all has returned to normal.
One thing that I've noticed has changed, is that a colon and a space after the colon are added automatically when you select a class marked as "property" from the popup menu. However, if you select a class marked as "local", no colon or space are added.

Regards
Martin

**Comment by matthew-dean** [comment]
That would be as designed. The "local" completer is a list of local compiled keywords (whole words from your document). The property completer is a CSS completer, which automatically completes with a colon. Each completer returns values separately, so there's not an easy way to remove duplication of a property and a local keyword.

**Comment by matthew-dean** [comment]
So, this is fixed?

**Comment by Pantyboy** [comment]
Hi Matt

Sorry, the extra space wasn't a complaint, far from it as I always add a space after the colon.

In answer to your question, yep, it's fixed.

Regards
