### ISSUE TITLE
double entries in source tree

### ISSUE THREAD

**Issue by manu37** [Crunch/Crunch-2#133]
As the title sais, double entries are displayed in source tree. Why?
![crunch](https://cloud.githubusercontent.com/assets/712682/11472991/405053c8-9770-11e5-81e7-6d5e78174c6f.JPG)

**Comment by matthew-dean** [comment]
Is this in RC1? It should have been fixed for the latest release.

**Comment by manu37** [comment]
just updated today to v 2.0.6-RC.1 (Win7x64). Same effect.

**Comment by matthew-dean** [comment]
Just looking at the code. If you already had duplicates in your ```.crunch``` file, it would still show the duplicates. But if you update your ```.crunch``` file (by re-crunching), it SHOULD then remove the duplicates and not happen again. But for sure let me know if it doesn't.

**Comment by manu37** [comment]
How do I re-crunch the .crunch file itself? Just re-crunching styles.less has no effect. Maybe I have to delete the .crunch file and reopen styles.less from new?

**Comment by manu37** [comment]
generating a new .crunch file still doubles..:
 ````   
{
	"files": {
		"src/less/styles.less": {
			"engines": [
				{
					"compiler": "less",
					"output": "../../dist/css/styles.css",
					"options": {
						"compress": false,
						"ieCompat": false,
						"strictMath": false,
						"strictUnits": false,
						"javascriptEnabled": false,
						"sourcemap": true
					}
				}
			],
			"sources": [
				"bootstrap/bootstrap.less",
				"bootstrap/buttons.less",
				"bootstrap/buttons.less",
				"bootstrap/code.less",
				"bootstrap/code.less",
				...
```

**Comment by matthew-dean** [comment]
Ah, I believe I found my mistake. Try this release and see if this is resolved: https://github.com/Crunch/Crunch-2/releases/tag/v2.0.7-RC.1

**Comment by manu37** [comment]
Hi Matthew
..still the same, even with 2.0.7.
Another strange thing: When I open my project from scratch, my less files are not visible the source directory:
![crunch](https://cloud.githubusercontent.com/assets/712682/11494724/83bdcad8-9805-11e5-91b0-20774f42ddfa.JPG)
Only after refreshing the view they show up.

**Comment by manu37** [comment]
Hi Matthew
..still the same, even with 2.0.7.
Another strange thing: When I open my project from scratch, my less files are not visible the source directory:
![crunch](https://cloud.githubusercontent.com/assets/712682/11494724/83bdcad8-9805-11e5-91b0-20774f42ddfa.JPG)
Only after refreshing the view they show up.

**Comment by matthew-dean** [comment]
Are you seeing the same issue in 2.0.8-RC.1 ?

**Comment by manu37** [comment]
In 2.0.8 the doubling issue is still there.

**Comment by matthew-dean** [comment]
Whaaat. The list is still doubled? Even if you a) Crunch a file, b) close the app and re-open? Still duplicate entries?

**Comment by matthew-dean** [comment]
Your other issue is tracked in #140.

**Comment by manu37** [comment]
Yes indeed, still the same. Closed all files, closed the app, deleted the .crunch file. Started from new, assigned the destination css file (1st crunch). ..and the entries are still doubled. crunch fille attached.
[crunch.zip](https://github.com/Crunch/Crunch-2/files/58379/crunch.zip)

**Comment by matthew-dean** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by matthew-dean** [comment]
@manu37 Would you be willing to include your project files (the files in src/less) in a zip file? If it's not too sensitive?

**Comment by manu37** [comment]
Here they are:
[srcLess.zip](https://github.com/Crunch/Crunch-2/files/62606/srcLess.zip)

**Comment by matthew-dean** [comment]
@manu37 Very helpful! I was able to reproduce and put in fixes for this for the next release (available shortly).
