### ISSUE TITLE
Uninstalled 

### ISSUE THREAD

**Issue by lexynyx** [Crunch/Crunch-2#143]
Hi there I was trying to uninstall the software and I did find the uninstall application, but when I double click it, nothing happens. I just makes my file explorer crash.

**Comment by matthew-dean** [comment]
That's odd. Thanks for reporting.

**Comment by matthew-dean** [comment]
I ran the uninstaller and I couldn't reproduce this.

**Comment by lexynyx** [comment]
hmm is there any other way to uninstall this software? I would try the control panel and uninstall it from there but the program doesnt show up there

**Comment by matthew-dean** [comment]
You could try installing a newer version and then running the uninstaller.

**Comment by matthew-dean** [comment]
The uninstaller is now available in Windows as of 2.1.3.
