### ISSUE TITLE
Close tab TypeError

### ISSUE THREAD

**Issue by sacerro** [Crunch/Crunch-2#150]
When all tabs are closed and you use the menu "Close Tab" TypeError is shown.

Yep, it's something rare (why I want to close tab when no tab is opened?) but I think it's a bug easy to solve (hope) ;)

![image](https://cloud.githubusercontent.com/assets/1681325/12126397/4ecd1056-b3f1-11e5-8140-20246c9455a4.png)

**Comment by matthew-dean** [comment]
Good find! Yes, it's small, so it'll come in a bugfix release instead of 2.0.

**Comment by sacerro** [comment]
Same error with Save / Save Us

**Comment by matthew-dean** [comment]
Thanks! Fixed in 2.0.13.
