### ISSUE TITLE
Find error when no file is open

### ISSUE THREAD

**Issue by sacerro** [Crunch/Crunch-2#151]
With menu Edit, Find action and no file opened menu panel dissapear

![image](https://cloud.githubusercontent.com/assets/1681325/12126581/47c15258-b3f2-11e5-9fc4-968ffe7d7455.png)

**Comment by matthew-dean** [comment]
How did you get to this result? And on which version?

**Comment by sacerro** [comment]
From menu and with latest version 2.0.12 on Win 10 x64

**Comment by matthew-dean** [comment]
Okay, so a number of "action on file" issues from menu when no file is present.

**Comment by matthew-dean** [comment]
Fixed in 2.0.13
