### ISSUE TITLE
What is wrong with your purchase system?

### ISSUE THREAD

**Issue by sgreenwalt** [Crunch/Crunch-2#154]
Great product. Terrible sales processing system.  I paid for a Pro upgrade license TWICE.  The first time, presented with a nice green checkbox at the end of the purchase, and then NO OBVIOUS MESSAGE regarding when to expect (or where to obtain) the product key.  Thinking it was possible that I entered incorrect payment info (and at the risk of $20 more), I gave it another shot under a different e-mail address.  SAME RESULT.  No confirmation e-mal received to either e-mail address. Yes, I check the spam folder.  NOW WHAT?

**Comment by matthew-dean** [comment]
That does sound terrible! Sorry about that. The payment processor is Stripe, and if there's any processing issue, it should at least pop up a message telling you what went wrong.

One small silver lining is that if you did not receive an email with an activation code, then something went wrong in processing the credit card, so you shouldn't have been charged at all. Not that that helps you completely, but that would mean you shouldn't see 2 charges on your CC bill.

I'm following up with Stripe to see where the issue might be. I'll post back what I find on this thread.

**Comment by sgreenwalt** [comment]
Thanks for the quick response.  It was a company card and possibly I used
the wrong name.  Will retry with correct info or use my own card.

On Thu, Jan 14, 2016 at 9:54 AM, Matthew Dean <notifications@github.com>
wrote:

> That does sound terrible! Sorry about that. The payment processor is
> Stripe, and if there's any processing issue, it should at least pop up a
> message telling you what went wrong.
>
> One small silver lining is that if you did not receive an email with an
> activation code, then something went wrong in processing the credit card,
> so you shouldn't have been charged at all. Not that that helps you
> completely, but that would mean you shouldn't see 2 charges on your CC bill.
>
> I'm following up with Stripe to see where the issue might be. I'll post
> back what I find on this thread.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Crunch/Crunch-2/issues/154#issuecomment-171701028>.
>



-- 
-----------------------------------------------------------------------------------------------
Stephen R. Greenwalt
801-678-1620
stephengreenwalt@gmail.com

**Comment by matthew-dean** [comment]
@sgreenwalt I don't think so. I just tried my card again, so I think something is borked. Looking at logs now.

**Comment by sgreenwalt** [comment]
ok, let me know.

On Thu, Jan 14, 2016 at 10:04 AM, Matthew Dean <notifications@github.com>
wrote:

> @sgreenwalt <https://github.com/sgreenwalt> I don't think so. I just
> tried my card again, so I think something is borked. Looking at logs now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Crunch/Crunch-2/issues/154#issuecomment-171705612>.
>



-- 
-----------------------------------------------------------------------------------------------
Stephen R. Greenwalt
801-678-1620
stephengreenwalt@gmail.com

**Comment by matthew-dean** [comment]
@sgreenwalt Okay, I just did several tests with my own credit card. It turned out that the Stripe payment page was just closing prematurely (before it finished processing). It should be working now.

Thanks for reporting it! It looks like from the logs that might have affected a number of people.

**Comment by matthew-dean** [comment]
@sgreenwalt Note: you'll need to restart Crunch 2 to complete the purchase.

**Comment by matthew-dean** [comment]
@sgreenwalt Also, if you can send me a private message somewhere with your email address, then I'll give you a 50% refund.

**Comment by matthew-dean** [comment]
Closed as fixed. Re-open if there are other issues.
