### ISSUE TITLE
Edit file error

### ISSUE THREAD

**Issue by datdotnet** [Crunch/Crunch-2#157]
I edit a html file and there is an error: type error: Can not read the property root of undefind -- oops ....
How to fix it?

**Comment by matthew-dean** [comment]
I believe this may be a duplicate of #156, where opening a file or creating one, while in Crunchable view, causes a TypeError. Were you in Crunchable View (tab flipped over)?

**Comment by matthew-dean** [comment]
This is fixed in 2.1.1.
