### ISSUE TITLE
Unhandled error on jade files, windows

### ISSUE THREAD

**Issue by jorge8168711** [Crunch/Crunch-2#163]
I can´t compile jade files on windows, i normally use prepros to work and i don't have this problem, i don't know what i am doing wrong.

![image](https://cloud.githubusercontent.com/assets/7266089/13409943/d6f6f0b2-defa-11e5-8dcf-73f980cbd63e.png)

**Comment by matthew-dean** [comment]
Can you post your jade file?

**Comment by jorge8168711** [comment]
[index.txt](https://github.com/Crunch/Crunch-2/files/152085/index.txt)
just change the extension

**Comment by matthew-dean** [comment]
Fixed: https://github.com/Crunch/Crunch-2/releases/tag/v2.1.3

**Comment by jorge8168711** [comment]
thanks a lot
