### ISSUE TITLE
Text cursor bug - text is entered before the letter on the left.

### ISSUE THREAD

**Issue by rachellcarbone** [Crunch/Crunch-2#165]
On PC - Windows 8.1 
Crunch 2 version - Version 2.1.5

Since updating to Crunch 2 I've noticed that the text cursor (blinking "|" that indicates where I'm typing) can become off by one.

To clarify If I click at the end of the line `ABC` after the `C`, the text cursor will appear to the right of the `C` as expected. But when start typing I would actually be adding letters before the letter `C`, so like this `ABnewlettershereC`

I cant seem find a pattern to find a patter to this bug but it can be very difficult to get it to stop as it sometimes stays buggy after restarting Crunch.

**Comment by TommyTheBlackbird** [comment]
It's happening to me too. (Windows 10 / Crunch 2.1.5)

Seems bug #39 again.

**Comment by matthew-dean** [comment]
I changed the text-rendering Chromium bug workaround for #39 in Crunch 2.0.12. I thought it was a suitable fix but it looks like maybe that was a bad idea. [sad trombone]

I'm going to try to leave in _both_ fixes and after testing it out, will hopefully have a new release out soon.

**Comment by matthew-dean** [comment]
@TommyTheBlackbird @rachellcarbone Can you verify that 2.2.0 addresses this? https://github.com/Crunch/Crunch-2/releases/tag/v2.2.0

**Comment by matthew-dean** [comment]
Seems to be fixed in Windows based on my testing.

**Comment by matthew-dean** [comment]
Closing due to no more activity.
