### ISSUE TITLE
Crunch2 misses last file import instruction in bootstrap.less 

### ISSUE THREAD

**Issue by RobertSelrach** [Crunch/Crunch-2#174]
When the file to be compiled is not in the same directory as the less files that are being imported crunch2 logs the last file to be imported as not found, e.g. the file being compiled is in one directory but the component less files are in a sub-directory, as shown below
>less
>bootstrap
.crunch
__main.less

All import files defined in __main.less are compiled except for the last one. If the __main.less file is moved into the bootstrap directory the file compiles OK.

**Comment by matthew-dean** [comment]
I'm not sure I fully understand. There's a file that's `@import`-ed that is a file not found? What do you mean "not compiled"? I have the feeling the behavior isn't related to directory structure.

**Comment by RobertSelrach** [comment]
Hi, thanks for your prompt reply. This evening I tried to replicate the error and capture screens to better illustrate the issue but Crunch2 has behaved impeccably. I haven't done anything different from the last few days so cannot understand it. I will close the issue.

Thanks.
