### ISSUE TITLE
"Save As" for crunching files should default to "current" project folder

### ISSUE THREAD

**Issue by matthew-dean** [Crunch/Crunch-2#18]
Reported by user in alpha 2:
> When saving a crunched file, the folder that is opened is not the one that opens by default (the open window is by default my home/root folder).

**Comment by smdimagerie** [comment]
Same is happening when doing (Cmd+N) a new file

**Comment by smdimagerie** [comment]
It got fixed with b4 (OS X.10.4)

**Comment by matthew-dean** [comment]
Yay!
