### ISSUE TITLE
Website/Download: Linux is not .deb

### ISSUE THREAD

**Issue by daniel-wtd** [Crunch/Crunch-2#181]
Hey all,
I really appreciate your editor. Looks nice and feels smooth.

But one thing bothers...
.deb Package Format is not Linux 32/64. It is Ubuntu/Debian and should be called so. 
Or maybe ".deb Download". 

There are at least 2 more very popular File Formats (.rpm and .tar.xz) which should be considered to be Linux =)

Best regards,
Daniel

**Comment by matthew-dean** [comment]
Well, that sounds like mostly a semantic argument. Linux doesn't have any native package manager, so all there are are Linux distributions which supply their own. And Ubuntu happens to be the most popular Linux distro currently.  If you want RPM packages added, track this issue: https://github.com/Crunch/Crunch-2/issues/182

**Comment by daniel-wtd** [comment]
It was just a thing of wording. There is no generic linux as you stated. So to clarify this, I recommend to change the description to Ubuntu or .deb-download. This will prevent a lots of confusion.

Best regards,
Daniel
