### ISSUE TITLE
rpm packages

### ISSUE THREAD

**Issue by daniel-wtd** [Crunch/Crunch-2#182]
Hey,
nice to see you supporting Ubuntu/Debian Systems.
Are you planning on packaging .rpm for Fedora/RedHat/CentOS, too?

Or are you interested in someone who will put some effort in? If so, please ping me :)

**Comment by matthew-dean** [comment]
Crunch 2 uses nw-builder for packaging. (https://github.com/nwjs/nw-builder) To add RPM support, the best way is to do a PR with that project and then drop a message if / when that's merged.
