### ISSUE TITLE
Activation Unsuccessful

### ISSUE THREAD

**Issue by Pantyboy** [Crunch/Crunch-2#188]
Hi Matt and/or Matt.

After my usual system spring clean (take system apart, clean components, format HDD, re-install software) I've tried to install Crunch and get a pop up shows the error message:

> Crunch 2 could not be activated. You've activated too many copies of Crunch 2. :(

but there's nowhere to deactivate, check or reset the activations.

Er, help?!

**Comment by matthew-dean** [comment]
Hmm, it appears you activated Crunch more than 10 times? Any reason why?

**Comment by Pantyboy** [comment]
I do lots of installing and deleting of software/documents and after a while my machine starts to act up, so I reformat the drive and start again.

**Comment by matthew-dean** [comment]
Can you give me part or all of your email address that I can find?

**Comment by Pantyboy** [comment]
Certainly. It's martincotterill@yahoo.co.uk.

**Comment by Pantyboy** [comment]
Any news?

**Comment by Pantyboy** [comment]
New popup this time.

> Activation Unsuccessful
> 
> Crunch 2 could not be activated. We can't seem to find a customer record matching that. :(

Does this mean I need to buy Crunch Pro again?

**Comment by matthew-dean** [comment]
Sorry, try again?

**Comment by Pantyboy** [comment]
Got rid of the new popup's (I put in the wrong License Key. Old age doesn't come by itself, I've found).
Still getting the 
> Activation Unsuccessful
>Crunch 2 could not be activated. You've activated too many copies of Crunch 2. :(
popup.

**Comment by matthew-dean** [comment]
Hmmm...... try restarting Crunch 2 and trying again? Should not be giving you that popup.

**Comment by Pantyboy** [comment]
Restarted Crunch and tried to activate. Only got the 'timed out' error this time.

**Comment by matthew-dean** [comment]
Do you have a firewall set up? I just re-activated a local copy.

**Comment by matthew-dean** [comment]
Oops, I migrated servers and I didn't update the DB connections. Try again!

**Comment by Pantyboy** [comment]
Yay!

That did it! Thanks.

**Comment by matthew-dean** [comment]
Great!
