### ISSUE TITLE
Using a non-quoted (unsupported) @import causes 'null' error

### ISSUE THREAD

**Issue by matthew-dean** [Crunch/Crunch-2#19]
From user:
> I use @import a lot for my files to keep a nice and clean structure. C2 keeps asking null.less. (while erroring). Made a null.less, and it seems its the only file included it the crunched file.

**Comment by smdimagerie** [comment]
It got fixed somewhere before b4 (OS X.10.4)

**Comment by matthew-dean** [comment]
Probably in the Less version? Thanks, closing.
