### ISSUE TITLE
New file button

### ISSUE THREAD

**Issue by smdimagerie** [Crunch/Crunch-2#20]
It would be nice to add a "Create a new file" button

**Comment by nblackburn** [comment]
See #37

**Comment by sacerro** [comment]
It would be nice that this "button" has some friends like crunch, etc. A float menu like this image.
![image](https://cloud.githubusercontent.com/assets/1681325/10686611/2174fa94-7966-11e5-8a37-bdf4f1897a0e.png)

**Comment by matthew-dean** [comment]
Done for next release (just the new file button).
