### ISSUE TITLE
File showing twice

### ISSUE THREAD

**Issue by smdimagerie** [Crunch/Crunch-2#21]
When I create a file from outside crunch, it displays twice (situation goes back to normal when closing and reopening)

![image](https://cloud.githubusercontent.com/assets/13382294/8749505/011b59a2-2c70-11e5-9fda-d0b0ab334a54.jpg)

**Comment by matthew-dean** [comment]
Interesting. Will check it out.

**Comment by matthew-dean** [comment]
I've temporarily disabled directory monitoring for the next beta, so you might not see this for a while, but I'll have to revisit when I figure out a better directory monitoring solution. (It turns out this is one of the things grinding down Windows' performance.)

**Comment by matthew-dean** [comment]
Fixed in beta 5.
