### ISSUE TITLE
Opening files via Finder bypasses Pro activation detection

### ISSUE THREAD

**Issue by zenimpulse** [Crunch/Crunch-2#22]
Steps to reproduce:
1. Open an unactivated copy of Crunch 2.
2. Through the shortcut (Cmd+O) or the menu bar (Open File), open a Pro-supported (.coffee, .scss, etc) file from a Finder file prompt.

Expected Result:
The file should fail to open, showing a CTA to upgrade to Crunch Pro.

Actual Result:
The file opens and can be compiled as if it were any other file.

**Comment by matthew-dean** [comment]
Fixed in beta 1
