### ISSUE TITLE
Wire Ctrl/Cmd+Enter as "Save All in Crunchable, then Crunch"

### ISSUE THREAD

**Issue by matthew-dean** [Crunch/Crunch-2#23]
Ctrl+Enter used to trigger Crunch in Crunch 1.x. Crunches are triggered on save, but one user reported being used to using Ctrl+Enter. So, it can essentially serve the same purpose by saving all files being edited in a crunchable and Crunching that project.

**Comment by TommyTheBlackbird** [comment]
+1

**Comment by matthew-dean** [comment]
Added to beta 8.
