### ISSUE TITLE
Windows key mappings are tied to only letter key presses.

### ISSUE THREAD

**Issue by zenimpulse** [Crunch/Crunch-2#25]
Keyboard shortcuts on Windows are being mapped to simply the letter and not Ctrl + Letter.

For example, typing "o" or "n" will bring up the open file dialog, or create a new file respectively.

**Comment by matthew-dean** [comment]
That is terrible. WHO IS RESPONSIBLE FOR THIS? I DEMAND ANSWERS.

**Comment by matthew-dean** [comment]
This seems to be fixed, but need confirmation since I didn't reproduce the original issue.

**Comment by matthew-dean** [comment]
Fixed in Mac and Windows.
