### ISSUE TITLE
When a folder doesn't exist Crunch does not work

### ISSUE THREAD

**Issue by smdimagerie** [Crunch/Crunch-2#34]
I use Transmit a lot, which is an FTP client that create virtual drive with my mac. When I open crunch, If I'm not connected to the server where I was working last, I cannot open Crunch II (b3), I have to close crunch, connect to the server and then reopen Crunch. It should at least close all projects.

**Comment by matthew-dean** [comment]
Okay, thanks for reporting this.

**Comment by matthew-dean** [comment]
Can you see if beta 4 fixes this?

**Comment by smdimagerie** [comment]
It got fixed with b4 (OS X.10.4)

**Comment by matthew-dean** [comment]
Great!
