### ISSUE TITLE
TODO: Menus Improvements - suggestions welcome

### ISSUE THREAD

**Issue by matthew-dean** [Crunch/Crunch-2#37]

**Comment by nblackburn** [comment]
Here is my thinking...

```yml
- File
  - New
    - File
    - Project
  - Open
    - File
    - Project
  - Save
  - Save As
  - Crunch
- Edit
  - Undo
  - Redo
  - Select all
  - Cut
  - Copy
  - Paste
  - Find
  - Replace
  - Go to
- Help
  - About
  - Upgrade (_only visible on free tier_)
  - Check for updates
```

**Comment by matthew-dean** [comment]
Makes sense. Ace has a bunch of editor commands too, just wondered what might be most important to surface. I don't want to do all of them, just maybe some,  but here's the list: https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts

**Comment by nblackburn** [comment]
Updated the based on #62

**Comment by matthew-dean** [comment]
Implemented in beta 8.
