### ISSUE TITLE
Crunch does nothing in File menu if file not yet crunched (should open save to dialog).

### ISSUE THREAD

**Issue by tzhu07** [Crunch/Crunch-2#45]
I open a less file. Then try to crunch. Nothing happens at all.

I'm on Windows 10.

**Comment by amatecha** [comment]
Yeah, you have to click the little button on the tab for the .less file and set a destination .css file first.  I feel like the menu item to Crunch should maybe give a warning as such when you try to Crunch before having set a destination for the compiled CSS.

**Comment by tzhu07** [comment]
That's not intuitive at all. When I go to File --> Crunch!, I should get a dialog box of where I want to save the crunched file.

**Comment by matthew-dean** [comment]
@tzhu07 That's true. That would be the desired functionality. I must have missed that.

**Comment by matthew-dean** [comment]
Awesomely fixed in beta 8.
