### ISSUE TITLE
Stripe iframe persists when closing popup

### ISSUE THREAD

**Issue by mbl-at** [Crunch/Crunch-2#57]
First problem
1. Go to settings
2. Click "Get Crunch 2 Pro!"
3. Click "Buy it"
4. Click "X" to close
5. Crunch 2 freezes
6. If there was a not saved file, and you try to close the program, "Don't Save"/"I'll go save things"  are disabled.

**Comment by matthew-dean** [comment]
What platform? Wait... click X to close... what X exactly? Can you screenshot it?

**Comment by mbl-at** [comment]
Windows 7 Home Premium(64 bit) - 6.1.7601 SP1 Build 7601
![git5](https://cloud.githubusercontent.com/assets/8981484/10038773/6e18b844-6198-11e5-9404-b8014f8b68d3.gif)

**Comment by matthew-dean** [comment]
Ah I see. Crunch isn't freezing exactly, there's an iframe in the way that's not being removed when you close the Stripe popup. I'll take a look.

**Comment by matthew-dean** [comment]
Fixed in beta 8
