### ISSUE TITLE
Middle click drag

### ISSUE THREAD

**Issue by nblackburn** [Crunch/Crunch-2#61]
![screenshot-1](https://cloud.githubusercontent.com/assets/2931085/10034098/cc9229a4-6185-11e5-9ca1-d603726081b5.png)

Upon clicking the middle mouse button and dragging, it is possible to reveal hidden windows (_settings_), nothing major but thought i would point it out as it's likely not intended behavior.

**Comment by matthew-dean** [comment]
o_O  Screenshot? Macs don't have middle buttons or middle-button mice so I'm not sure how to reproduce.

**Comment by nblackburn** [comment]
![screenshot-1](https://cloud.githubusercontent.com/assets/2931085/10034098/cc9229a4-6185-11e5-9ca1-d603726081b5.png)

**Comment by matthew-dean** [comment]
Oh wow. It must be dragging the entire page somehow. If it snaps back when you release the button, then it's kind of odd behavior but not overly concerning.

**Comment by nblackburn** [comment]
@matthew-dean It doesn't snap back, you have to drag it back into place but it seems it's scrolling the page like it would in a browser.

**Comment by matthew-dean** [comment]
Hmm....

Technically, Crunch 2 is running in a "browser". It's running off the NW.js platform, which combines Node.js with Chromium (Google Chrome), so the interface is all HTML / CSS / JS. Crunch 1 was also web-based, but it was running off the much shittier Adobe AIR platform. (Although, to be fair, projects like NW.js didn't exist at the time.)

It sounds like the middle mouse button is wired in Chrome to scroll the "body" element. The messages and settings are off the visible area of the app, but are part of the page body. I can probably crop it to prevent that.

**Comment by nblackburn** [comment]
@matthew-dean Oh i am aware of the Abomination that is Adobe Air (_the reason i didn't use it before because i really don't like that platform_) don't you worry and am eternally grateful you decided make it web based.

**Comment by nblackburn** [comment]
I think i would put the settings in a model window which removes this issue

**Comment by matthew-dean** [comment]
Nah, that wouldn't really remove the issue.

**Comment by matthew-dean** [comment]
Probably fixed in beta 9.

**Comment by sacerro** [comment]
Yep, it's solved.

**Comment by matthew-dean** [comment]
Hooray!

**Comment by nblackburn** [comment]
AWESOME!
