### ISSUE TITLE
Delete projects

### ISSUE THREAD

**Issue by nblackburn** [Crunch/Crunch-2#62]
The ability to delete projects would be nice to have or detect ones that no longer exist on startup and remove them automatically.

**Comment by matthew-dean** [comment]
The projects view is really "Recent Projects" so it's also a history of what's opened. But I guess it's not unreasonable to what to remove something from history.

**Comment by nblackburn** [comment]
@matthew-dean I agree with "History should not be tampered with" but if a project seizes to exist, it seems logical to save real estate where possible.

**Comment by matthew-dean** [comment]
My only concern with that is that there may be scenarios where a folder is not currently accessible but is still important, such as detachable media. It might be better to require manual deletion.

**Comment by TommyTheBlackbird** [comment]
What about a "Close project" to remove it from the recent (opened projects?) list?

**Comment by nblackburn** [comment]
This could be linked to #37 by including a Project menu which contains...

```yml
- Project
  - Open
  - Close
```

**Comment by stuartxt** [comment]
Really need to be able to delete projects. Having many jobs that come and go, I don't need to have all of them accessable all the time. The ones that I have deleted from my Mac I really don't need at all, but they are still on the list :(
If a containing directory gets renamed or moved you could 're-link' it.

**Comment by matthew-dean** [comment]
@stuartxt Fair enough. I'll make something awesome for it.

**Comment by matthew-dean** [comment]
Remove projects right-click menu added to beta 9.
