### ISSUE TITLE
Regression: (beta 6) Search does not show the result list

### ISSUE THREAD

**Issue by TommyTheBlackbird** [Crunch/Crunch-2#65]
The search only shows the number of matches found but not the results list.

(Crunch beta 6 - Windows 10/64bits )

![crunch2-beta6-search](https://cloud.githubusercontent.com/assets/14106278/10048806/f6fa3e5e-6214-11e5-9122-78a0fca2d7ac.gif)

**Comment by matthew-dean** [comment]
Well poopers.

**Comment by matthew-dean** [comment]
I'll try to get an update to beta 6 soon for this particular bug.

**Comment by matthew-dean** [comment]
Fixed in beta 7
