### ISSUE TITLE
Request: handy shortcuts

### ISSUE THREAD

**Issue by TommyTheBlackbird** [Crunch/Crunch-2#66]
May be we can feed a list of handy shortcuts.

- "Close file/tab" CTRL+W (or middle mouse)
- "Crunch" CTRL+Enter (I miss this one.... but CTRL+S does the job)
 
(btw, Ace editor shortcuts are great! A shortcut list within Crunch like Crunch 1 would be great)

**Comment by matthew-dean** [comment]
I'd actually really be interested in what are common "tab management" shortcuts between different pieces of software. We'd have to choose ones that don't conflict with Ace shortcuts, but that's certainly something I would like.

**Comment by matthew-dean** [comment]
Ctrl+Enter has been added.

**Comment by matthew-dean** [comment]
Close Tab added to beta 9.
