### ISSUE TITLE
Duplicated entries in dependency files list

### ISSUE THREAD

**Issue by TommyTheBlackbird** [Crunch/Crunch-2#71]
When expanding a less source magic tab, in the dependecy files list appears some duplicated entries.

(btw, related with #65 , the search works fine from this view,)

![crunch2b6_bug_dup_files](https://cloud.githubusercontent.com/assets/14106278/10158774/7d829286-6694-11e5-9ac9-19086aef1b05.png)

**Comment by matthew-dean** [comment]
Hmm. This was filed with the directory view, but not for the magic tab / crunchable view. I'll have to see if I can reproduce it. Any tips you can give me on what you were doing when that happened, or why it might be that some are duplicated and some not? (As in, save / edit operations with certain files?)

**Comment by matthew-dean** [comment]
Fixed in beta 7
