### ISSUE TITLE
Name Error in navbar.less in bootstrap 2

### ISSUE THREAD

**Issue by SSteve** [Crunch/Crunch-2#73]
I get an error trying to compile navbar.less from bootstrap 2. Here's an excerpt that gives an error on line 8:

```
@gridColumns:             12;

// Reset container width
// Required here as we reset the width earlier on and the grid mixins don't override early enough
.navbar-static-top .container,
.navbar-fixed-top .container,
.navbar-fixed-bottom .container {
  #grid > .core > .span(@gridColumns);
}
```

**Comment by matthew-dean** [comment]
You can't compile bootstrap subfiles individually. You have to compile the base file (bootstrap.less). You're referencing a variable that navbar.less doesn't have access to.

**Comment by SSteve** [comment]
When I was originally compiling, I wasn't trying to compile the subfile individually. The code in my report is an excerpt that illustrated the error I was running into. It uses the variable `gridColumns` but I defined that at the top of the excerpt. You'll get the same error if you try compiling **bootstrap.less** from https://github.com/twbs/bootstrap/releases/tag/v2.3.2

**Comment by matthew-dean** [comment]
Oh okay, sorry I misunderstood.

I would think that's probably a compatibility issue between that particular version of Bootstrap and the current version of Less. Crunch just feeds the file you want to compile to the Less compiler and reports success or error from that compiler (and allows you to link to it in the code). Are there any errors reported with that version in either Less or Bootstrap Github repos?

**Comment by SSteve** [comment]
Thanks for the clarification. I'll check with the Less and Bootstrap repos.
