### ISSUE TITLE
In App Purchase?

### ISSUE THREAD

**Issue by inspiredmac** [Crunch/Crunch-2#74]
I downloaded the Version 2 Pro copy, but I can't locate any in-app purchase option. How do I pay for a registered copy?

**Comment by inspiredmac** [comment]
By the way, I clicked on the Crunch Settings cog and got a Get Crunch button to upgrade to Pro, but it's inactive.

**Comment by matthew-dean** [comment]
Hmm... I looked at this today, and this shouldn't be possible for the button to be disabled unless something else is blocking the UI. I'm putting out a new beta soon, so tell me if that fixes it.

**Comment by matthew-dean** [comment]
Also will surface this a little better. Closing in favor of #75.
