### ISSUE TITLE
How do I tell which version and beta number

### ISSUE THREAD

**Issue by Pantyboy** [Crunch/Crunch-2#76]
Hi Matt

I think I've found a couple of issues but I don't know which beta version I'm using.

The window tells me I'm using Crunch 2 Pro but that all.

How do I tell which version I have?

Regards

**Comment by matthew-dean** [comment]
On the Mac there's a Crunch > About Crunch option. But I don't think that exists on Windows. The best way is just install the latest (beta 7) and see if you can replicate your issues.

**Comment by Pantyboy** [comment]
I'll give it a go.

Thanks Matt (or Matt).

**Comment by matthew-dean** [comment]
It's just Matt.

**Comment by Pantyboy** [comment]
It's always good to know who you're talking to. It's easy to make a mistake otherwise.

**Comment by Pantyboy** [comment]
Just to let you know, I uninstalled the program, cleaned out the system, reinstalled Crunch and all is normal.
