### ISSUE TITLE
Uninstaller

### ISSUE THREAD

**Issue by Pantyboy** [Crunch/Crunch-2#77]
Hi again

I was about to do an uninstall/re-install of Crunch 2 Pro but no shortcut entry appears in the Windows 10 Start Menu or within Control Panel's Programs and Features.

There is an uninstall .exe program in the Crunch directory.

Just thought I'd let you know.

Pb

**Comment by matthew-dean** [comment]
Oh, I see, it didn't link anywhere the uninstaller executable.

**Comment by Pantyboy** [comment]
I meant too mention this earlier.

The links to launch Crunch and uninstall Crunch are two separate entries on the Windows 10 start menu (under "All apps"). Maybe these would be better if grouped in one start folder. ie:

 |-- Crunch 2
 |------ Crunch 2
 |------ Uninstall Crunch 2

Just a thought.

Reagrds

**Comment by matthew-dean** [comment]
@Pantyboy The Windows installer setup is a little unfamiliar to me, but I think I've made the correct changes for the next beta.

**Comment by matthew-dean** [comment]
Will close for now. Re-open if not fixed.
