### ISSUE TITLE
Crunch not create compiled files

### ISSUE THREAD

**Issue by pavolhudran** [Crunch/Crunch-2#82]

**Comment by matthew-dean** [comment]
Are you running into issue #45?

**Comment by pavolhudran** [comment]
Hi,

no i solve it, but i couldn’t find a way how to delete it, so i delete text :)

Bye

**Comment by matthew-dean** [comment]
How did you solve it, and what do you mean, you couldn't find a way to delete it. You mean the .css file?

**Comment by pavolhudran** [comment]
I forget how to convert LESS to CSS, so i thought that application didn’t work. I thought it will convert automatically after saving. But before you must set output file. So i set it and it is working.

With deleting i meant, that i couldn’t find how to delete all issue, so i deleted text within.

**Comment by matthew-dean** [comment]
Closing as duplicate of #45.
