### ISSUE TITLE
Can't close the About dialog

### ISSUE THREAD

**Issue by TommyTheBlackbird** [Crunch/Crunch-2#95]
The "Interesting!" button does nothing. 
Any way it was pretty fun to read all the nerdy stuff :smile:

**Comment by sacerro** [comment]
And when you read all those funny jokes, the "Ok" button doesn't work to... Now I don't want to know anything about Crunch hehehe

**Comment by Pantyboy** [comment]
I have to close Crunch to get rid of the "About" dialog. Have to say though, I did enjoy going through the "interesting" screens.

**Comment by matthew-dean** [comment]
Duplicate of https://github.com/Crunch/Crunch-2/issues/91. It's fixed and will ship with the next beta.
