### ISSUE TITLE
Go to Line Prompt

### ISSUE THREAD

**Issue by sacerro** [Crunch/Crunch-2#96]
When you use shortcut of Go to Line (ctrl + L) the prompt message has bad title (prompt) and you need to focus the input for insert the line number. When you use "Enter" key the input is not send, you need to use the "Ok" button.

**Comment by matthew-dean** [comment]
Yep, I think right now it does a regular html prompt. It should look more like the find window.

**Comment by matthew-dean** [comment]
Fixed.
