### ISSUE TITLE
Can't delete proyect from panel when directory is not accesible

### ISSUE THREAD

**Issue by sacerro** [Crunch/Crunch-2#98]
I move the folder of my project and now I can't delete project from recent files. Error:

 Whoops! Directory "~\git\Paracelso\wp-content\themes\paracelso\library\less" is not accessible.

**Comment by matthew-dean** [comment]
Ah, okay. Thanks for reporting.

**Comment by matthew-dean** [comment]
Hmm, sorry, can't replicate this. I created a folder, added it as a project, deleted the folder, and was able to right-click and remove the project.

**Comment by sacerro** [comment]
This project was created with other beta, but now with latest version (beta 9) I can't delete.

If I made a new project and I delete or move the folder I can erase project...

**Comment by sacerro** [comment]
With beta 10 I cant delete it!! I think it's solved by some kind of magic hehe

Thanks for your work

**Comment by matthew-dean** [comment]
Do you mean you *can* delete it?

**Comment by sacerro** [comment]
Delete the project from Recent list.

**Comment by matthew-dean** [comment]
Okay, closing, thanks!
