### ISSUE TITLE
UI/UX polish

### ISSUE THREAD

**Issue by nblackburn** [Crunch/Crunch-2#99]
For the final release it would be nice to polish up some of the UI/UX inconsistencies so that everything fits within the design language of the application.

- [ ] Custom scroll bars
- [ ] Custom menu
- [ ] The autocomplete box should be styled in accordance with the active theme.

This is obviously not a hugely important thing but would help to keep everything visually consistent.

**Comment by matthew-dean** [comment]
"Custom menu"?

**Comment by matthew-dean** [comment]
I had a look at scrollbars, and tinkered with a custom component. It confirmed for me that it's very high risk to change at this time. Trust me, after years of implementing different custom scrolling solutions, it can be a massive bag of hurt. And more importantly, if a scroll component breaks, it renders the app unusable.

**Comment by nblackburn** [comment]
No worries, i will close this as it's not massively important like i said.

**Comment by matthew-dean** [comment]
@nblackburn The big issue with scrollbars was that they didn't seem to work with Ace initially with styling the default ones, so that's what seemed so tricky. However, once updating Ace, I was able to just use webkit scrollbar styling. Looks pretty good (on Mac anyway). Will ship with RC1.

**Comment by nblackburn** [comment]
@matthew-dean Awesome, glad you got it working!
